# Generated by Django 3.2.8 on 2021-11-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboards', '0019_remove_material_material_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
